### ISSUE TITLE
Virtualbox 4.3 is not longer supported

### ISSUE THREAD

**Issue by CesarF** [UnaCloud/UnaCloud2#9]
It is necessary adding support for vbox 5.0 in UnaCloud due to 4.3 is not longer supported. Function "execute" used to run commands in guest is deprecated.

**Comment by hcastrob** [comment]
Seguro? La gente si actualiza vbox tan juiciosamente?

De: César Forero [mailto:notifications@github.com]
Enviado el: lunes, 27 de marzo de 2017 8:51 p. m.
Para: UnaCloud/UnaCloud2 <UnaCloud2@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Asunto: [UnaCloud/UnaCloud2] Virtualbox 4.3 is old version without support (#9)


It is necessary adding support for vbox 5.0 in UnaCloud due to 4.3 is not longer supported. Function execute to run commands in guest is deprecated.

**Comment by CesarF** [comment]
Vbox 5 support in UnaCloud will be released in version 2.1.1.
